version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./:/app  # Bind mount for development
      - app_data:/app/data  # Named volume for persistent data
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=llama3.2
      - REDIS_URL=redis://redis:6379
      - DEBUG=true
    depends_on:
      ollama:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - rag-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama  # Named volume for Ollama models
    networks:
      - rag-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rag-network
    command: redis-server --save 60 1 --loglevel warning

networks:
  rag-network:
    driver: bridge

volumes:
  ollama_models:
    name: ollama_models
  app_data:
    name: rag_app_data
  redis_data:
    name: rag_redis_data